name: Support Ticket
description: Submit a new ticket for support
title: "[support]: "
labels: ["recieved"]
projects: ["lalewis1/2"]
assignees:
  - lalewis1
body:
  - type: markdown
    attributes:
      value: |
        We will endeavour to resolve your issue swiftly
  - type: checkboxes
    id: broken
    attributes:
      label: Is something broken?
      options:
        - label: Is something broken
          required: true
        - label: Was it working before
          required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Details of the support request
      placeholder: ex. the codebase is on fire
    validations:
      required: true
